# Generated by Django 5.1.4 on 2024-12-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=200)),
                ('release_year', models.DateField(blank=True, null=True)),
                ('genre', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Movies',
        ),
    ]
